#!/usr/bin/env python3
"""Emit best_prime/_fundamentals.py (fundamental D with bounded class number).

Deterministic form enumeration. Does not call PARI, Sage, or cm.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_OUT = ROOT / "best_prime" / "_fundamentals.py"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--d-max", type=int, default=40000)
    p.add_argument("--h-max", type=int, default=128)
    p.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()

    from best_prime.classpoly import class_number
    from best_prime.primality_ecpp import _is_fundamental_discriminant

    rows: list[tuple[int, int]] = []
    for absd in range(3, args.d_max + 1):
        d = -absd
        if d % 4 not in (0, 1):
            continue
        if not _is_fundamental_discriminant(d):
            continue
        h = class_number(d)
        if 2 <= h <= args.h_max:
            rows.append((d, h))

    lines = [
        '"""Fundamental discriminants with bounded class number.\n',
        "\n",
        "Generated by scripts/generate_fundamentals.py (reduced primitive\n",
        "forms). Deterministic. No PARI/Sage/cm.\n",
        '"""\n',
        "\n",
        "from __future__ import annotations\n",
        "\n",
        f"D_CATALOG_MAX = {args.d_max}\n",
        f"H_CATALOG_MAX = {args.h_max}\n",
        "\n",
        "# (D, h(D)), increasing |D|.\n",
        "FUNDAMENTAL_DH: tuple[tuple[int, int], ...] = (\n",
    ]
    lines.extend(f"    ({d}, {h}),\n" for d, h in rows)
    lines.append(")\n")
    args.output.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {args.output} ({len(rows)} discriminants)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
